# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4b98d625a1028e81a03991668676957578d73808a02c706bf77fd4e9c69290f75218678d44ca70770c04ae46820342202bac35067e7f8fd0ce1e5bbcb89795e

test:
  secret_key_base: 0065e067e83aa1e115cf7b9dd82f6958bd90740dd1aea53595979d154c545f19852695305c254bbf23b685a2d34f68b601c6c53e7b6517cf5e3dc4e306ac8f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
