# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11724c8a6b63958ac4a6e4aff32d204b1b4a490ee39fdeee705306b7b70338561971fd33b289711f9cd4e438552f465623ab668734b678384938bfc118d2d0db

test:
  secret_key_base: f172c58d2916a4645acb5586bc68c3d16c241d46b577f65604413d421d169b952561cca6973913fd949b1b493227a857116092dd916fd80c94ce7c157ee01bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
